ECHO OFF
maisBarata.exe Instancias/att48INFO.TXT Instancias/att48.txt
maisBarata.exe Instancias/berlin52INFO.TXT Instancias/berlin52.txt
maisBarata.exe Instancias/kroA100INFO.TXT Instancias/kroA100.txt
maisBarata.exe Instancias/kroA150INFO.TXT Instancias/kroA150.txt
maisBarata.exe Instancias/kroA200INFO.TXT Instancias/kroA200.txt
maisBarata.exe Instancias/kroB100INFO.TXT Instancias/kroB100.txt
maisBarata.exe Instancias/kroB150INFO.TXT Instancias/kroB150.txt
maisBarata.exe Instancias/kroB200INFO.TXT Instancias/kroB200.txt
maisBarata.exe Instancias/kroC100INFO.TXT Instancias/kroC100.txt
maisBarata.exe Instancias/kroD100INFO.TXT Instancias/kroD100.txt
maisBarata.exe Instancias/kroE100INFO.TXT Instancias/kroE100.txt
maisBarata.exe Instancias/lin105INFO.TXT Instancias/lin105.txt
maisBarata.exe Instancias/pr107INFO.TXT Instancias/pr107.txt
maisBarata.exe Instancias/pr124INFO.TXT Instancias/pr124.txt
maisBarata.exe Instancias/pr136INFO.TXT Instancias/pr136.txt
maisBarata.exe Instancias/pr144INFO.TXT Instancias/pr144.txt
maisBarata.exe Instancias/pr152INFO.TXT Instancias/pr152.txt
maisBarata.exe Instancias/pr76INFO.TXT Instancias/pr76.txt
maisBarata.exe Instancias/rat195INFO.TXT Instancias/rat195.txt
maisBarata.exe Instancias/rat99INFO.TXT Instancias/rat99.txt